---
name: Ansible Test
on:
  push:
    branches: [ main, "stable*", "rebrand" ]
  pull_request:
    branches: [ main, "stable*", "rebrand" ]
  workflow_dispatch:

jobs:
  sanity:
    name: Sanity Tests (Ansible Core 2.17+)
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible Core 2.17+
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible-core>=2.17.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/cdot65/scm

      - name: Install dependencies
        run: |
          cd ansible_collections/cdot65/scm
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          fi
          # Install test dependencies
          if [ -f "requirements-test.txt" ]; then
            python -m pip install -r requirements-test.txt
          fi

  #      - name: Run sanity tests
  #        run: |
  #          cd ansible_collections/cdot65/scm
  #          ansible-test sanity --docker default --python 3.11 --skip-test ansible-doc --allow-disabled

  units:
    name: Unit Tests (Ansible Core 2.17+)
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: sanity

    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible Core 2.17+
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible-core>=2.17.0

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/cdot65/scm

      - name: Install dependencies
        run: |
          cd ansible_collections/cdot65/scm
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt
          fi
          # Install test dependencies
          if [ -f "requirements-test.txt" ]; then
            python -m pip install -r requirements-test.txt
          fi

#      - name: Run unit tests
#        run: |
#          cd ansible_collections/cdot65/scm
#          if [ -d "tests/unit" ]; then
#            ansible-test units --docker default --python 3.11
#          else
#            echo "No unit tests found, skipping"
#            exit 0
#          fi
